### ISSUE TITLE
licensing needs to be flexible

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#176]
Some datasets will be CC-BY, and some will be -NC. To get this to work, we need:

- [x] homepage license needs a link to a licensing FAQ question
- [x] FAQ needs to say that some datasets are -NC
- [x] contributors page needs a field for license, with default being no license, but a big NC logo for certain datasets, and something in the policy about this
- [x] wordbankr / apps need more citation support (telling you what the cite is for a dataset by default as a column) plus a "license" column with CC-BY and CC-BY-NC

this last is up for discussion, but I think I am learning that there is long-standing anxiety in the community about depositing data with databases that you lose credit, so the stronger our credit norms and citation tools, the more we will get data.

**Comment by mcfrank** [comment]
I think that wordbankr should just return the license as a `message` not as a column (e.g., "some datasets in this download are licensed CC-BY-NC and should not be used for commercial purposes" when you ask for Japanese or Korean). That is a bit lighter weight?

**Comment by daniellekellier** [comment]
I've been reading up on the CC website. It looks like we can add a 'license' field to the database. Perhaps default is "" or "BY" with the option of "BY-NC". We would need to use their official logo on the contributors page next to each dataset covered by "BY-NC" [this one](https://mirrors.creativecommons.org/presskit/icons/by.large.png). 

Besides that we need to update the FAQ and the footer to say something along the lines of "**Unless otherwise stated**, data is covered by a CC BY License. Datasets labeled with this logo mean they are covered by a CC BY-NC License". Or something along these lines to make sure we comply with CC. And from there we could tweak wordbankr to remind people if one of the datasets pulled has a "BY-NC" license. 

Does this sound like what you wanted?
