### ISSUE TITLE
clinical population functionality

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#179]
- [x] need a "developmental status" field in the child table 
- [x] need a selectize box for "developmental status" with "typically developing" the default that filters other status, but allows the inclusion of other developmental status, and makes this a facet variable (for norms app)
- [x] wordbankr needs this filter functionality as well in the get_admins methods etc.

**Comment by mcfrank** [comment]
@mikabr @daniellekellier @amsan7 Tagging you guys for thoughts. 

we also should figure out if we can import summary-level data (e.g., just totals) and have NA for the individual items. @vmarchman has this for several datasets. 

Once we get these things resolved, we have a bunch of DD datasets, including NDAR data from around 3k kids on the autism spectrum.

**Comment by vmarchman** [comment]
We currently have:  (1) Adamson/Bakeman, (2) Edgin, (3) Focus Foundation, (4) Elison/Day

**Comment by mikabr** [comment]
This shouldn't be that hard to do, since the by-item data is in its own table, so database population code can in principle just not create that table, only add to the administrations table. Most of the changes to support this would be to the db population code, with a few changes in wordbankr and the shiny apps as well.
