### ISSUE TITLE
wordbank-master.zip    broken archive !

### ISSUE THREAD

**Issue by bobjtowers** [langcog/wordbank#182]
-rw-rw-r-- 1 hwbh hwbh 278921216 Apr 17 20:55 wordbank-master.zip
hwbh@acer:~/wordbank$ unzip wordbank-master.zip 
Archive:  wordbank-master.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of wordbank-master.zip or
        wordbank-master.zip.zip, and cannot find wordbank-master.zip.ZIP, period.

**Comment by mcfrank** [comment]
@bobjtowers are you trying to download the entire archive from github? you could clone the repository instead. but why would you want to host a local copy of the dataset? 

(or if that's not what you're trying to do, can you tell us what you are hoping to accomplish?)

**Comment by mcfrank** [comment]
Hi @bobjtowers, 

The "clone and download" button is provided by github, not by us. I'm not sure why it's not working, but it's not part of wordbank. "Downloading the archive" is not usual functionality, that's why I'm asking. To my knowledge there isn't anyone running a local copy of wordbank outside of our research group. 

Let me suggest that if installing git is onerous, hosting a full mysql database and django server to run a local copy is going to be much moreso. It is possible to set up a local copy of the site, but it's going to require a *lot* of install work. You can't just download and poke at it - setting up the database locally requires running all the migrations. You might consider downloading one of the sql version images if you want to run a sql server. 

But really the best way to work with the data you want is to download them via the API and save them locally through R.
