### ISSUE TITLE
some summary data for W&G missing

### ISSUE THREAD

**Issue by ebergelson** [langcog/wordbank#183]
hey, we were hoping to look at the trajectories for these two items, but somehow kids have 0s across all months on the by-word data summary: 
![image](https://user-images.githubusercontent.com/11085620/39276316-87126b44-48b6-11e8-8e10-07a3d6011db2.png)

maybe the non-word data aren't available? otherwise, seems like a potential bug...

**Comment by daniellekellier** [comment]
The by-word graph looks for items that fall neatly into the 'understands' vs 'produces' bins. Items that are not words don't fall into that. First_signs and phrases look at whether a child understands the item. Starting_to_talk looks at whether a child produces. That's not talking about gesture items and their 5 different response categories. 
![image](https://user-images.githubusercontent.com/19960439/39328240-969301ac-494f-11e8-8975-ebc89bf1cabd.png)
Since this shiny app has you pick the measure you are interested in , either "Understands" or "Produces", how would we best represent non-word items? For example, phrases only looks at comprehension so would all 'phrases' items be scored as 0 automatically if we pick the "Produces" measure?

**Comment by mcfrank** [comment]
good question. also - the best way to get this might be to use wordbankr -
you should be able to do `get_item_data` for the language you want and then
filter to those particular items.

Mike

**Comment by ebergelson** [comment]
would it break everything to have those other categories like phrases or starting to talk selectable on the right? or to have 'understands' 'produces' and 'other'? just a thought.

**Comment by mcfrank** [comment]
I think we have to limit to words - it is eventually in the works to make a
browser for these non-word items. The trouble is that many languages do
this very differently and the special cases (three, four categories, weird
response options, etc.) mean there is a lot of extra gunk in the item
browser stuff.

**Comment by daniellekellier** [comment]
Limited app to word items only in 4f8754d22c4c783d0fa4e09a9d41f26bcac083c4
