### ISSUE TITLE
irish bilingual data

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#207]
Thanks to the generosity of Ciara O'Toole and with solicitation from Josh Hartshorne, we have Irish/English bilingual data from the ICDI. Data are in .SAV (SPSS) format. From Ciara: "Attached is an SPSS file with the data and you will see the child code and session code (which means the 1st, 2nd, 3rd or 4th time them completed the ICDI) and then some other background information as well as all the total Irish, English and Conceptual vocabulary scores (so if they know any item in both languages they were only credited once)."

ICDI form: [ICDI_WS_2015_Final_Jan 16.pdf](https://github.com/langcog/wordbank/files/6359602/ICDI_WS_2015_Final_Jan.16.pdf)

[MANUAL for ICDI Words and Sentences Website_Feb2018.pdf](https://github.com/langcog/wordbank/files/6359592/MANUAL.for.ICDI.Words.and.Sentences.Website_Feb2018.pdf)
[O'Toole & Hickey 2017.pdf](https://github.com/langcog/wordbank/files/6359593/O.Toole.Hickey.2017.pdf)

[WandSAllVariables_n=140_WordBank.sav.zip](https://github.com/langcog/wordbank/files/6359596/WandSAllVariables_n.140_WordBank.sav.zip)

**Comment by mcfrank** [comment]
Citation is: Ciara O’Toole, Daniela Gatt, Tina M. Hickey, Aneta Miękisz, Ewa Haman, Sharon Armon-Lotem, Tanja Rinker, Odelya Ohana, Christophe dos Santos & Sophie Kern (2017) Parent report of early lexical production in bilingual children: a cross-linguistic CDI comparison, International Journal of Bilingual Education and Bilingualism, 20:2, 124-145, DOI: 10.1080/13670050.2016.1179258

**Comment by ningkko** [comment]
@HenryMehta Hi Henry I'm here to help with preparing the data for Wordbank. I cleaned the Irish data into two files as attached. Could you take a look to see what else we need?
[index.csv](https://github.com/langcog/wordbank/files/6402646/index.csv)
[irish.xlsx](https://github.com/langcog/wordbank/files/6402647/irish.xlsx)

**Comment by HenryMehta** [comment]
@ningkko Sorry for the delay replying.  I'm not quite in a position to reply yet because, but I have seen this and will respond this week I hope

**Comment by HenryMehta** [comment]
@ningkko Again, please accept my apologies for the delay (which has been considerably longer than I expected).  I am sorry that this is another holding response, but I should be on it soon.  I have written the code in order to load multi-lingual data (both 1. testing the child in 2 languages and associated both sets of results with the same child and 2. adding a language exposure component when only 1 language has been tested), but I have not written the instructions for how data is to be presented to enable that.  I am about to do that over the next couple of days

**Comment by HenryMehta** [comment]
@ningkko 
I have now updated the Wiki to explain how data needs to be presented.  It can be found [here](https://github.com/langcog/wordbank/wiki/DEVELOPMENT---Instructions-will-multilingual-added/_edit).  

I do not understand what the index.csv file is, so I am going to ignore it for now.

I need the .xlsx file changed slightly.  The way we import the language exposure data is a field which contains the language, proportion of time on the language and age of acquisition.  Your language field has something like Irish Only, Mostly Irish, Equal Irish and English, Mostly English and English Only (I think).  I need you to make a judgement about what proportion and age to assign to each of these and since some children have two languages you would need 2 columns.  For example, let's create two columns called language1 and language2, for a child with Equal Irish and English the columns might be completed as "Irish;50;0" and "English;50;0" whereas for a child with English Only you would have "English,100,0" and a blank in language2 .

I can make these changes if you give me the proportions you want.

We also need to convert your education levels into the Wordbank scales (you may have already done this).  These are the scales used by Wordbank:  `{(1, 'None'), (2, 'Primary'), (3, 'Some Secondary'), (4, 'Secondary'), (5, 'Some College'), (6, 'College'), (7, 'Some Graduate'), (8, 'Graduate')}`.  Can you confirm if these are the same as your data or provide me with a conversion.

Finally, I need an csv file that relates the words asked with the available responses.  This is described in detail within the Instrument section of the link above.  I cannot do this for you because I do not know what the words are, the type of word, possible responses or anything else.

I hope this is ok.  Please come back to me with any questions

**Comment by ningkko** [comment]
@HenryMehta Hi Henry, I just saw this. I'll get back to you by the end of this week.

**Comment by ningkko** [comment]
@HenryMehta Hi Henry, 
>> Add the instrument to static/json/instruments.json with an entry such as
I didn't find the file, not even the static folder?

**Comment by HenryMehta** [comment]
@ningkko 
I'll do the instruments.json file.

Within the data you show mothers (I think) education level.  I need clarification on how your data ties into the Wordbank classifications.

**Comment by ningkko** [comment]
@HenryMehta Hi Henry, I didn't quite understand the fields.csv and values.csv. I have the instruction file and data file ready. It seems that the information asked in the fields and values file is contained in the data file. Could you have a look at these two files and see what else I need to add
[Irish_English_data.csv](https://github.com/langcog/wordbank/files/6804583/Irish_English_data.csv)
[Irish_English.csv](https://github.com/langcog/wordbank/files/6804584/Irish_English.csv)
?

**Comment by HenryMehta** [comment]
@ningkko Sorry for the months delay - these look like I've enough info to get working on these

**Comment by HenryMehta** [comment]
@alvinwmtan @ningkko Within the EnglishIrishWS_OToole_data.csv file there are entries with values on 2, 9, 11, 3 and 10.  I have set all these to blank in the values file.  Also the load is currently failing because English (Irish) has no field name item_332.  I don't know if you want me to add this to the EnglishIrish.csv file or move it from English data file to Irish data file

**Comment by HenryMehta** [comment]
On the Irish side, I have values 2, 9, 12 and 3 which I've set to blank.  And the load crashes on item_331 so same question as English side.

Finally I've loaded the datasets with         
        ```
"splitcol": false,
"norming": false,
"longitudinal": false,
```
Please confirm this is correct

**Comment by HenryMehta** [comment]
@alvinwmtan @ningkko 
This is now loaded - it would be good if you could check and confirm data looks good when you pull it out with R.  Thanks

**Comment by alvinwmtan** [comment]
@HenryMehta Data checked from R; this dataset is good to go!
