### ISSUE TITLE
lexical categories

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#208]
@georgialoukatou and I were looking at the "other" category, and it includes `sounds`, `games and routines`, `time words`, `people`, and `places`. This is a bit weird... at least `places` should probably be in nouns, right? Also maybe `time words`? People I guess is a bit idiosyncratic and could stay in "other" but ...  @mikabr @kachergis @vmarchman

**Comment by kachergis** [comment]
agreed -- Alex and I noticed that and recategorized for some of the Noun vs. Verb stuff we did; can share if it's useful

**Comment by georgialoukatou** [comment]
@kachergis Yes, it would be great if you could share, thanks!

**Comment by vmarchman** [comment]
@kachergis <https://github.com/kachergis>  @georgialoukatou
<https://github.com/georgialoukatou> @mikabr <https://github.com/mikabr> "

Bates et al (1994) never had an "other" category, but rather excluded
certain categories of nominals from the noun category to limit it to
"common nouns".  The only categories were: common nouns, predicates and
closed class.  "other" was not a coherent category and therefore not
analyzed further. The justification is here (p. 95):Fig. I summarizes
developmental trends in vocabulary composition for
three variables: percentage of common nouns, percentage of predicates, and
percentage of closed-class items. COMMON NOUNS were defined to include the
following categories from the CDI: animal names, vehicles, toys, clothing,
body parts, small household items, food and furniture (280 possible items,
41.3 % of the total checklist). Potential nominals that were excluded from
this
category include games and routines (e.g. pattycake), sound effects (e.g.
meow, vroom), names for people (e.g. proper nouns and items like
babysitter), and places to go (a category which included some common nouns
but also included adverbials like outside and gerunds like camping), These
items were excluded because previous studies have suggested that they may
follow a different developmental course from 'true nominals' (Snyder, Bates
& Bretherton, 1981; Bates et al. 1988).....
6:56 <https://langcog.slack.com/archives/C0128NC1MHQ/p1619186185015700>

**Comment by kachergis** [comment]
sorry, took me a while to dig it up (and it was simpler than I remembered...):

`
verbs <- get_item_data(language = "English (American)", form = "WS") %>%
  filter(lexical_class == "verbs")

#also include the nouns marked as "other"
nouns <- get_item_data(language = "English (American)", form = "WS") %>%
  filter(lexical_class == "nouns" | category == "people" | category == "places")
`

**Comment by mikabr** [comment]
are there database-level changes needed here?

**Comment by mikabr** [comment]
if I understand correctly, for some analyses it makes sense to reclassify (some) people and places as "nouns" rather than "other", but it makes sense for the lexical category coding in the db to stay as is (which is the Bates et al (1994) categorization)
