### ISSUE TITLE
Incorrect values for some instruments

### ISSUE THREAD

**Issue by alvinwmtan** [langcog/wordbank#246]
Following up from #215, some instruments have incorrect, truncated values. These are as follows:

- English (American) WS: `understa`
- French (Quebecois) WS: `understa`
- Russian WG: `understan`
- Spanish (Mexican) WS: `not`, `som` (probably `not yet` and `sometimes`)
- Dutch Swingley: `understa`, `underst`, `unders`, `produce`, `produc`
- Dutch WG: `unde`
- Dutch FormThree: `prod`
- Spanish (Argentinian) WS: `prod`

There are also some instruments with `0` instead of `""` (empty string):

- Dutch WS, WG, FormOne, FormTwoA, FormTwoB, FormThree

Finally, there are two other value errors:

- French (Quebecois) WS: `NA` (as a character string)
- Slovak WG: `never ` (with an extra space at the end)

**Comment by HenryMehta** [comment]
@alvinwmtan @mikabr @mcfrank @vmarchman 

There is some specification within the original coding of Wordbank which is causing some (and I think the majority) of these issues.  It is in the application of the language specification file (eg `[English_WS].csv`.

I shall used English (American) WS to walk through it.  

Most items within `[English_WS].csv` are defined as having `choices` of `produces`.  

1. When we run `02_create_instrument_schemas` this creates a field `models.CharField(max_length=8 choices=item_xxx_choices, null=True)`.  So the maximum length of an entry is 8 characters.  This means when we try to save `understands`, we only save `understa`.   From a code perspective, this is unchanged from pre Wordbank2, but I don't know if earlier version of Python/Django didn't enforce the constraint.  We have this problem across many datasets.
2. It also sets a choices constraint limiting the choices to `produces`, (`item_xxx_choices = [('produces', 'produces')]`) but this is only applied across forms and not when data is entered via code.  So if `understands` is given as an option in the `_values.csv` file for a dataset, then the constraint is ignored.

I need to know as a general principle if the `choices` defined within the original language specification file (in this case `[English_WS].csv`) should be applied or ignored.

**Comment by HenryMehta** [comment]
I have corrected the program and rerun the Dutch and Spanish Argentinian.  They should be ok now.

The database specification for Irish and English Irish were wrong and have been corrected.

Slovak WG had 'never ' within the values file.  I have amended and reloaded.  It should be ok now

French Quecois WS had NA within the values file.  I have amended to blank ('') and reloaded

These three issues (English (American) WS: understa, French (Quebecois) WS: understa, Russian WG: understan) are because of the issue I mentioned above where the [language].csv file is stating the only 'produces' should be available so I need to know if that definition of choices should be ignored or if the load program should be amended to throw out an error if we're trying to load a value not available in the choices given in the [language].csv file

**Comment by alvinwmtan** [comment]
@HenryMehta I think the best theoretical solution is to ignore choice definitions within `[language].csv`. This is because researchers sometimes use forms in somewhat non-standard ways (e.g. recording "understands" on WS forms from a population that is not typically developing), so we should honour the `xxx_values.csv` instead.

**Comment by alvinwmtan** [comment]
@HenryMehta all of these look fine except Spanish (Mexican)—this stills has "som", "not", and "sometimes/o". the field length may need to be longer because some forms have "sometimes/often" as an option

**Comment by HenryMehta** [comment]
@alvinwmtan Amended - I think this is now ok

**Comment by alvinwmtan** [comment]
@HenryMehta looks great, thanks!
