### ISSUE TITLE
standardize NULL vs blank in data

### ISSUE THREAD

**Issue by mikabr** [langcog/wordbank#60]
different things are happening in various instruments/datasets/item types, need to think through what the data should really look like and change models & data import accordingly

**Comment by mikabr** [comment]
Need more logic in the data import code that handles this. In words data there should be blanks (and probably no NULLs?) In wordform/complexity sections, the logic that's currently implemented in the cdi-grammar analyses should be in the data import, something like:
- if data is all blank and kid combines, then all blank=NULL
- if data is all blank and kid doesn't combine, then all blank=1
- if data has a mix of blanks and not blanks, then blank=1

**Comment by mikabr** [comment]
Clearer way of stating this:
Treating item data "normally" is to convert any zeros/blanks/NAs/NULLs/whatever to our zero value, blank.
For all items other than the complexity section, treat them normally.
For the complexity section, look at the "combines" item. If it's "yes", treat the complexity items normally. If it's "no", all of the complexity items should be NA/NULL.

**Comment by mcfrank** [comment]
> For the complexity section, look at the "combines" item. If it's "yes", treat the complexity items normally. If it's "no", all of the complexity items should be NA/NULL.

This looks a little different than I thought - I thought the logic was "if there are ANY positive items in the complexity section, treat blank as 'less complex option' - if there are NO positive items in the complexity section, treat blank as 'blank'"

Mike

**Comment by vmarchman** [comment]
Don't know if this is good news or bad news......

I just looked at the English norming data.  There are the same number of
valid kids for the complexity score as
for the vocab.  This would not be the case if a completely blank complexity
section was treated as missing in the case of not combining.  For English
(at least), a "blank" complexity section was treated as a valid score of 0
(not missing).

In fact, we have a couple hundred kids with combining = 0 who had a valid 0
on complexity (whose moms stopped per the instructions and left the
complexity section blank), and a couple hundred who were combining = 1 with
a complexity = 0, either because mom left it blank or chose the less
complex option in each case.

I know we were worried about "true" missing data, but in the English, we
did not assume that a blank = missing in any case for complexity.

We did have missing for combining and M3L (in the case of mom said combine
= 1, but did not provide example sentences).


On Mon, Apr 20, 2015 at 4:25 PM, Michael Frank <notifications@github.com>
wrote:

> > For the complexity section, look at the "combines" item. If it's "yes",
> treat the complexity items normally. If it's "no", all of the complexity
> items should be NA/NULL.
>
> This looks a little different than I thought - I thought the logic was "if
> there are ANY positive items in the complexity section, treat blank as
> 'less complex option' - if there are NO positive items in the complexity
> section, treat blank as 'blank'"
>
> Mike
>
> > On Apr 20, 2015, at 1:02 PM, Mika Braginsky <notifications@github.com>
> wrote:
> >
> > Clearer way of stating this:
> > Treating item data "normally" is to convert any
> zeros/blanks/NAs/NULLs/whatever to our zero value, blank.
> > For all items other than the complexity section, treat them normally.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/langcog/wordbank/issues/60#issuecomment-94591482>.
>



-- 

*********************************
Virginia A. Marchman, Ph.D.
marchman@stanford.edu
Research Associate
Center for Infant Studies
Psychology
Stanford University
Stanford, CA  94305
650-723-1257
*********************************

**Comment by mcfrank** [comment]
Hi Virginia, 

Thanks for checking the English data. So are you saying we should just always treat blank = 0 on the complexity section? 

best,

Mike

**Comment by vmarchman** [comment]
Hi - I'm saying that's what we did for the English, and most likely the
Spanish (I can check that) as well.  It forces the grammar section to be 0
for a lot of kids, but that makes sense developmentally.  To allow
reasonable crosslinguistic comparisons, we should probably apply a
consistent strategy....

-vm

**Comment by mcfrank** [comment]
Virginia, 

I agree - but we need to have a way to keep from doing that for the particular datasets where no one filled out complexity... otherwise our analyses get dragged down by developmentally-inappropriate 0s, too. 

Mike

**Comment by mikabr** [comment]
I'm getting confused, so I made this table:
 | Combines | Doesn't combine
------------ | ------------ | -------------
All blanks | blank=NA | blank=simple
Mix of blanks and values | blank=simple | blank=simple
Is this what we want? Which of these cases might be problematic?

**Comment by mcfrank** [comment]
It may vary by dataset whether combines is even marked, no? 

Mike

**Comment by mikabr** [comment]
True...

 | Combines | Doesn't combine | Unknown
------------ | ------------ | ------------- | -------------
All blanks | blank=NA | blank=simple | blank=?
Mix of blanks and values | blank=simple | blank=simple | blank=?

**Comment by mikabr** [comment]
Virginia's table:

| Combines      |       Doesn't combine       |     Unknown
-- | -- | -- | --
All blanks         |         blank=simple    |     blank=simple        |          blank = NA
Mix of blanks/values blank=simple     |    blank = simple        |        blank = NA

**Comment by mcfrank** [comment]
True...

 | Combines | Doesn't combine | Unknown
------------ | ------------ | ------------- | -------------
All blanks | blank=simple | blank=simple | blank=NA
Mix of blanks and values | blank=simple | blank=simple | blank=simple
