### ISSUE TITLE
word data report

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank#98]
this is a report that shows mean # of kids knowing at each age, with age across the horizontal. each word is a column. you can sort by form class, CDI cats, etc. 

need filters on top for language, instrument, label, etc.

**Comment by mikabr** [comment]
First pass up at http://54.149.39.46:3838/item_data/

**Comment by mcfrank** [comment]
It looks great - it’s just quite slow (10s+ latencies) and seems to load the data twice always, with a pause for reformatting? 

Do we need more caching, or is the server just having a bad day? 

Mike

**Comment by mikabr** [comment]
There are a few reasons for the speed issues -- the loading data twice thing is because of some reactivity resolution stuff that's really hard to debug, but I'll give it a try. Also it's on the dev server, which is a lot less beefy than the prod server. But generally most of the lag is in needing to load all the kid x item data... we could cache the proportions, but would need to do it for every age. We could also revisit the design issues and see if we can make it faster?
